### ISSUE TITLE
Cookie problem

### ISSUE THREAD

**Issue by yeci226** [vermaysha/hoyoapi#54]
I was able to use the cookie normally a little earlier. After the cookie expired, I tried to change the cookie, but I found that no matter whether I set the v1 or v2 cookie, the error HoyoAPIError: Cookie key ltuid or ltoken doesn’t exist !

**Comment by vermaysha** [comment]
Please remember to include the ltuid and ltoken cookies.

**Comment by yeci226** [comment]
> Please remember to include the ltuid and ltoken cookiee and please upgrade to version 1.1.1.

i upgraded to 1.1.1. Cookie V1 can be used normally, but sometimes when Cookie V2 is obtained, it cannot be used normally

**Comment by WafuRuns** [comment]
Can confirm that V2 cookies throw the `HoyoAPIError: Cookie key ltuid or ltoken doesn’t exist !` error and V1 cookies will, on the other hand, throw the `HoyoAPIError: You must set options.cookie.cookieTokenV2 to access this API` error. Doesn't feel like there's a consistent solution.

**Comment by vermaysha** [comment]
> > Please remember to include the ltuid and ltoken cookiee and please upgrade to version 1.1.1.
> 
> i upgraded to 1.1.1. Cookie V1 can be used normally, but sometimes when Cookie V2 is obtained, it cannot be used normally


After further investigation, it turns out that cookieTokenV2 always changes constantly. Therefore, it is not suitable for use in certain situations.

Perhaps we can ignore cookieTokenV2 and explicitly fill in the UID.

Note: CookieTokenV2 is only used in the Hoyolab class.

**Comment by yeci226** [comment]
> > > Please remember to include the ltuid and ltoken cookiee and please upgrade to version 1.1.1.
> > 
> > 
> > i upgraded to 1.1.1. Cookie V1 can be used normally, but sometimes when Cookie V2 is obtained, it cannot be used normally
> 
> After further investigation, it turns out that cookieTokenV2 always changes constantly. Therefore, it is not suitable for use in certain situations.
> 
> Perhaps we can ignore cookieTokenV2 and explicitly fill in the UID.
> 
> Note: CookieTokenV2 is only used in the Hoyolab class.

May I ask when Cookie v2 can be used normally?
Because in most cases the cookies obtained are v2 and cannot be used

**Comment by jokelbaf** [comment]
> May I ask when Cookie v2 can be used normally? Because in most cases the cookies obtained are v2 and cannot be used

Most likely on any endpoint. HoYo were rolling out Cookie v2 since last year. Now HoYoLab is entirely using v2 instead of v1.

However, cookie v1 can still be used. But as far as I know, for some users v1 causes errors or returns nothing sometimes. 

The problem is that this library requires you to pass v1 cookie for some reason. My solution was to implement password authorization for my users and obtain both v1 and v2 cookies + `stoken` which I use to refresh v1 cookie.

**Comment by ShinoMythmaker** [comment]
> > May I ask when Cookie v2 can be used normally? Because in most cases the cookies obtained are v2 and cannot be used
> 
> Most likely on any endpoint. HoYo were rolling out Cookie v2 since last year. Now HoYoLab is entirely using v2 instead of v1.
> 
> However, cookie v1 can still be used. But as far as I know, for some users v1 causes errors or returns nothing sometimes.
> 
> The problem is that this library requires you to pass v1 cookie for some reason. My solution was to implement password authorization for my users and obtain both v1 and v2 cookies + `stoken` which I use to refresh v1 cookie.

But this simply doesnt fix the issue that v2 needs to be refreshed every once in a while.

**Comment by jokelbaf** [comment]
> > > May I ask when Cookie v2 can be used normally? Because in most cases the cookies obtained are v2 and cannot be used
> > 
> > 
> > Most likely on any endpoint. HoYo were rolling out Cookie v2 since last year. Now HoYoLab is entirely using v2 instead of v1.
> > However, cookie v1 can still be used. But as far as I know, for some users v1 causes errors or returns nothing sometimes.
> > The problem is that this library requires you to pass v1 cookie for some reason. My solution was to implement password authorization for my users and obtain both v1 and v2 cookies + `stoken` which I use to refresh v1 cookie.
> 
> But this simply doesnt fix the issue that v2 needs to be refreshed every once in a while.

From my knowledge, only cookie token needs to be refreshed. And there is nothing you can do with it because this is how they deal with guys like us who creates bots and applications using libraries like this one. 

Best thing you can do at this point is obtain new cookie via request to hoyo's API using `account` & `password` of your users stored somewhere on your side. However, you will need to solve geetest — either by forcing users to do it manually or by using services like 2captcha. But this solution is awful and expensive so I guess you should just forget about routes which use cookie token.
